.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

        Click :ref:`here <sphx_glr_download_auto_examples_QESR.py>`     to download the full example code
    .. rst-class:: sphx-glr-example-title

    .. _sphx_glr_auto_examples_QESR.py:


Quantitative ESR
================
In this example, we baseline correct and
integrate ESR data, and compare the result to
the result of integration inside XEPR.

This makes use of the package `pint`, which is a
very nice package for handling units.



.. rst-class:: sphx-glr-horizontal


    *

      .. image:: /auto_examples/images/sphx_glr_QESR_001.png
          :alt: absorption, direct
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_002.png
          :alt: d_abs. int, direct
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_003.png
          :alt: for baseline
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_004.png
          :alt: absorption, with baseline
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_005.png
          :alt: dblint ÷ denom
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_006.png
          :alt: dblint
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_007.png
          :alt: dblint, normed → check for ⅓
          :class: sphx-glr-multi-img

    *

      .. image:: /auto_examples/images/sphx_glr_QESR_008.png
          :alt: compare my QESR to Bruker
          :class: sphx-glr-multi-img


.. rst-class:: sphx-glr-script-out

 Out:

 .. code-block:: none

    G_R 81 dB
     C_t 4.0 ms
     power 2.0 mW
     B_m 2.0 G
     Q 4500.0
     n_B 1
     S 0.5
     c 1
     signal_denom 152012311.1661785 G·W⁰⋅⁵·s 152012311.1661785
    peaksize 2.3925781279922376
    specrange (3494.4472657918905, 3531.0683595876894)
    C:\Users\johnf\notebook\pyspecdata\examples\QESR.py:86: RankWarning: Polyfit may be poorly conditioned
      c = d_baseline.polyfit(fieldaxis, order=7)
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 133: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 102, in <module>
        fl.plot(d_abs/norm, alpha=0.5)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2018, in plot
        firstarg = self.check_units(args[0],0,1) # check units, and if need be convert to human units, where x is the first dimension and y is the last
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2047, in check_units
        logger.debug(strm("called check_units for figure",self.current))
    Message: 'called check_units for figure dblint, normed\n→ check for ⅓'
    Arguments: ()
    G_R 81 dB
     C_t 4.0 ms
     power 2.0 mW
     B_m 2.0 G
     Q 4600.0
     n_B 1
     S 0.5
     c 1
     signal_denom 155390362.52542692 G·W⁰⋅⁵·s 155390362.52542692
    peaksize 2.5390625031755008
    specrange (3494.300781416707, 3531.0683595876894)
    C:\Users\johnf\notebook\pyspecdata\examples\QESR.py:86: RankWarning: Polyfit may be poorly conditioned
      c = d_baseline.polyfit(fieldaxis, order=7)
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 121: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1937, in next
        logging.debug(strm("I'm changing to figure",self.get_fig_number(name),"for",name))
    Message: "I'm changing to figure 7 for dblint, normed\n→ check for ⅓"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 133: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 102, in <module>
        fl.plot(d_abs/norm, alpha=0.5)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2018, in plot
        firstarg = self.check_units(args[0],0,1) # check units, and if need be convert to human units, where x is the first dimension and y is the last
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2047, in check_units
        logger.debug(strm("called check_units for figure",self.current))
    Message: 'called check_units for figure dblint, normed\n→ check for ⅓'
    Arguments: ()
    G_R 81 dB
     C_t 4.0 ms
     power 2.0 mW
     B_m 2.0 G
     Q 4600.0
     n_B 1
     S 0.5
     c 1
     signal_denom 155390362.52542692 G·W⁰⋅⁵·s 155390362.52542692
    peaksize 2.441406253053325
    specrange (3494.4472657918905, 3531.0683595876894)
    C:\Users\johnf\notebook\pyspecdata\examples\QESR.py:86: RankWarning: Polyfit may be poorly conditioned
      c = d_baseline.polyfit(fieldaxis, order=7)
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 121: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1937, in next
        logging.debug(strm("I'm changing to figure",self.get_fig_number(name),"for",name))
    Message: "I'm changing to figure 7 for dblint, normed\n→ check for ⅓"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 133: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 102, in <module>
        fl.plot(d_abs/norm, alpha=0.5)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2018, in plot
        firstarg = self.check_units(args[0],0,1) # check units, and if need be convert to human units, where x is the first dimension and y is the last
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2047, in check_units
        logger.debug(strm("called check_units for figure",self.current))
    Message: 'called check_units for figure dblint, normed\n→ check for ⅓'
    Arguments: ()
    G_R 81 dB
     C_t 4.0 ms
     power 2.0 mW
     B_m 2.0 G
     Q 5500.0
     n_B 1
     S 0.5
     c 1
     signal_denom 185792824.7586626 G·W⁰⋅⁵·s 185792824.7586626
    peaksize 2.441406253053325
    specrange (3494.5937501670737, 3530.921875212506)
    C:\Users\johnf\notebook\pyspecdata\examples\QESR.py:86: RankWarning: Polyfit may be poorly conditioned
      c = d_baseline.polyfit(fieldaxis, order=7)
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 121: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1937, in next
        logging.debug(strm("I'm changing to figure",self.get_fig_number(name),"for",name))
    Message: "I'm changing to figure 7 for dblint, normed\n→ check for ⅓"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 133: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 102, in <module>
        fl.plot(d_abs/norm, alpha=0.5)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2018, in plot
        firstarg = self.check_units(args[0],0,1) # check units, and if need be convert to human units, where x is the first dimension and y is the last
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2047, in check_units
        logger.debug(strm("called check_units for figure",self.current))
    Message: 'called check_units for figure dblint, normed\n→ check for ⅓'
    Arguments: ()
    G_R 81 dB
     C_t 4.0 ms
     power 2.0 mW
     B_m 2.0 G
     Q 5600.0
     n_B 1
     S 0.5
     c 1
     signal_denom 189170876.11791104 G·W⁰⋅⁵·s 189170876.11791104
    peaksize 2.441406253053325
    specrange (3494.5937501670737, 3530.921875212506)
    C:\Users\johnf\notebook\pyspecdata\examples\QESR.py:86: RankWarning: Polyfit may be poorly conditioned
      c = d_baseline.polyfit(fieldaxis, order=7)
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 121: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1937, in next
        logging.debug(strm("I'm changing to figure",self.get_fig_number(name),"for",name))
    Message: "I'm changing to figure 7 for dblint, normed\n→ check for ⅓"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 133: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 102, in <module>
        fl.plot(d_abs/norm, alpha=0.5)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2018, in plot
        firstarg = self.check_units(args[0],0,1) # check units, and if need be convert to human units, where x is the first dimension and y is the last
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2047, in check_units
        logger.debug(strm("called check_units for figure",self.current))
    Message: 'called check_units for figure dblint, normed\n→ check for ⅓'
    Arguments: ()
    G_R 81 dB
     C_t 4.0 ms
     power 2.0 mW
     B_m 2.0 G
     Q 5400.0
     n_B 1
     S 0.5
     c 1
     signal_denom 182414773.39941418 G·W⁰⋅⁵·s 182414773.39941418
    peaksize 2.441406253053325
    specrange (3494.5937501670737, 3530.921875212506)
    C:\Users\johnf\notebook\pyspecdata\examples\QESR.py:86: RankWarning: Polyfit may be poorly conditioned
      c = d_baseline.polyfit(fieldaxis, order=7)
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 121: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 101, in <module>
        fl.next("dblint, normed\n→ check for ⅓")
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1937, in next
        logging.debug(strm("I'm changing to figure",self.get_fig_number(name),"for",name))
    Message: "I'm changing to figure 7 for dblint, normed\n→ check for ⅓"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 133: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 102, in <module>
        fl.plot(d_abs/norm, alpha=0.5)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2018, in plot
        firstarg = self.check_units(args[0],0,1) # check units, and if need be convert to human units, where x is the first dimension and y is the last
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2047, in check_units
        logger.debug(strm("called check_units for figure",self.current))
    Message: 'called check_units for figure dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 263: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 108, in <module>
        fl.next('compare my QESR to Bruker')
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1979, in next
        logger.debug(strm('added figure',len(self.figurelist)+1,'because not in figurelist',self.figurelist))
    Message: "added figure 8 because not in figurelist ['absorption, direct', 'd_abs. int, direct', 'for baseline', 'absorption, with baseline', 'dblint ÷ denom', 'dblint', 'dblint, normed\\n→ check for ⅓']"
    Arguments: ()
    Bruker: 190.80 Ours: 193.24
    Bruker: 172.10 Ours: 172.67
    Bruker: 177.70 Ours: 175.75
    Bruker: 173.20 Ours: 172.07
    Bruker: 144.60 Ours: 144.76
    Bruker: 155.90 Ours: 153.04
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 251: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 119, in <module>
        print("Bruker: %04.2f Ours: %04.2f"%(QESR_concs[j]/1e-6,myconcs[j]/m_hardcode/1e-6))
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2395, in __exit__
        self.show()
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2160, in show
        logger.debug(strm("before show_prep, figlist is",self.figurelist))
    Message: "before show_prep, figlist is ['absorption, direct', 'd_abs. int, direct', 'for baseline', 'absorption, with baseline', 'dblint ÷ denom', 'dblint', 'dblint, normed\\n→ check for ⅓', 'compare my QESR to Bruker']"
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 119: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 119, in <module>
        print("Bruker: %04.2f Ours: %04.2f"%(QESR_concs[j]/1e-6,myconcs[j]/m_hardcode/1e-6))
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2395, in __exit__
        self.show()
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2166, in show
        logger.debug(strm("showing figure \"%s\""%lsafen(figname)))
    Message: 'showing figure "dblint, normed\n→ check for ⅓ \n\n"'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 112: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 119, in <module>
        print("Bruker: %04.2f Ours: %04.2f"%(QESR_concs[j]/1e-6,myconcs[j]/m_hardcode/1e-6))
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2395, in __exit__
        self.show()
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2167, in show
        self.next(figname)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1918, in next
        logger.debug(strm("for plot",input_name,"basename is",self.basename))
    Message: 'for plot dblint, normed\n→ check for ⅓ basename is None'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 135: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 119, in <module>
        print("Bruker: %04.2f Ours: %04.2f"%(QESR_concs[j]/1e-6,myconcs[j]/m_hardcode/1e-6))
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2395, in __exit__
        self.show()
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2167, in show
        self.next(figname)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1929, in next
        logger.debug(strm('with basename appended, this is',name))
    Message: 'with basename appended, this is dblint, normed\n→ check for ⅓'
    Arguments: ()
    --- Logging error ---
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
        stream.write(msg + self.terminator)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 121: character maps to <undefined>
    Call stack:
      File "C:\ProgramData\Anaconda3\Scripts\sphinx-build-script.py", line 9, in <module>
        sys.exit(main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 294, in main
        return build_main(argv)
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
        app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 278, in __init__
        self._init_builder()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\application.py", line 337, in _init_builder
        self.events.emit('builder-inited')
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\events.py", line 110, in emit
        results.append(listener.handler(self.app, *args))
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 419, in generate_gallery_rst
        this_fhindex, this_costs = generate_dir_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 361, in generate_dir_rst
        intro, title, cost = generate_file_rst(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 835, in generate_file_rst
        output_blocks, time_elapsed = execute_script(script_blocks,
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 756, in execute_script
        output_blocks.append(execute_code_block(
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 583, in execute_code_block
        mem_max, _ = gallery_conf['call_memory'](
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_gallery.py", line 187, in call_memory
        return 0., func()
      File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_gallery\gen_rst.py", line 496, in __call__
        exec(self.code, self.fake_main.__dict__)
      File "C:\Users\johnf\notebook\pyspecdata\examples\QESR.py", line 119, in <module>
        print("Bruker: %04.2f Ours: %04.2f"%(QESR_concs[j]/1e-6,myconcs[j]/m_hardcode/1e-6))
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2395, in __exit__
        self.show()
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 2167, in show
        self.next(figname)
      File "c:\users\johnf\notebook\pyspecdata\pyspecdata\core.py", line 1937, in next
        logging.debug(strm("I'm changing to figure",self.get_fig_number(name),"for",name))
    Message: "I'm changing to figure 7 for dblint, normed\n→ check for ⅓"
    Arguments: ()






|


.. code-block:: default

    from pyspecdata import *
    import numpy as np
    from matplotlib.pyplot import axvline, axhline, gca
    from pint import UnitRegistry

    ureg = UnitRegistry(system="mks",autoconvert_offset_to_baseunit=True, auto_reduce_dimensions=True)

    Q_ = ureg.Quantity
    colors = plt.rcParams["axes.prop_cycle"]() # this is the default matplotlib cycler for line styles
    fieldaxis = '$B_0$'
    pushout = 3
    QESR_concs = r_[190.8,
            172.1,
            177.7,
            173.2,
            144.6,
            155.9,]*1e-6
    myconcs = []
    with figlist_var() as fl:
        background = find_file("QESR_Test_WaterCap_Background_210923.DSC", exp_type="francklab_esr/Sam")['harmonic',0]
        #background -= background[fieldaxis, -100:].data.mean()
        for filenum, (thisfile, thislabel) in enumerate([("QESR_150uM_TEMPOL_1_noglyc_210923.DSC", "sample #1"),
                ("QESR_150uM_TEMPOL_2_noglyc_210923.DSC", "sample #2"),
                ("QESR_150uM_TEMPOL_3_noglyc_210923.DSC", "sample #3"),
                ("QESR_150uM_TEMPOL_4_wglyc_210923.DSC", "sample #4"),
                ("QESR_150uM_TEMPOL_5_wglyc_210923.DSC", "sample #5"),
                ("QESR_150uM_TEMPOL_6_wglyc_210923.DSC", "sample #6"),
                ]):
            d = find_file(thisfile, exp_type="francklab_esr/Sam")['harmonic',0]
            G_R = Q_(*d.get_prop("Gain"))
            C_t = Q_(*d.get_prop("ConvTime"))
            # it seems like n is already divided out
            #n = Q_(1,'dimensionless') # Q_(float(d.get_prop('AVGS')),'dimensionless')
            power =  Q_(*d.get_prop("Power"))
            B_m = Q_(*d.get_prop("ModAmp"))
            Q = Q_(float(d.get_prop('QValue')),'dimensionless')
            #Q = Q_(5400.,'dimensionless')
            n_B = Q_(1,'dimensionless') # calculate this
            S = Q_(0.5,'dimensionless')
            c = Q_(1,'dimensionless') # the first fraction on pg 2-17 -- essentially the conversion factor
            signal_denom = G_R * C_t * sqrt(power) * B_m * Q * n_B * S * (S+1)
            signal_denom = signal_denom.to(Q_('G')*sqrt(Q_('W'))*Q_('s'))
            print(
                    f"G_R {G_R:~P}\n",
                    f"C_t {C_t:~P}\n",
                    f"power {power:~P}\n",
                    f"B_m {B_m:~P}\n",
                    f"Q {Q:~P}\n",
                    f"n_B {n_B:~P}\n",
                    f"S {S:~P}\n",
                    f"c {c:~P}\n",
                    f"signal_denom {signal_denom:~P} {signal_denom.magnitude}")
            d.set_plot_color(next(colors)['color'])
            #d -= d[fieldaxis, -100:].data.mean()
            d -= background
            fl.next("absorption, direct")
            d_abs = d.C.integrate(fieldaxis, cumulative=True)
            fl.plot(d_abs, alpha=0.5)
            peaklist = d_abs.contiguous(lambda x: abs(x) > abs(x).data.max()/2)[:3,:]
            peaksize = np.diff(peaklist, axis=1).mean()
            print("peaksize",peaksize)
            specrange = (peaklist.ravel().min(),peaklist.ravel().max())
            print("specrange",specrange)
            fl.next("d_abs. int, direct")
            d_int_direct = d_abs.C
            fl.plot(d_int_direct.integrate(fieldaxis, cumulative=True), alpha=0.5)
            fl.next("absorption, direct")
            generous_limits = specrange+r_[-pushout*peaksize,+pushout*peaksize]
            for j in r_[np.array(specrange), generous_limits]:
                axvline(x=j/1e3, alpha=0.1)
            d_baseline = d_abs[fieldaxis, lambda x: np.logical_or(x<generous_limits[0], x>generous_limits[1])]
            fl.next("for baseline")
            fl.plot(d_baseline, '.', alpha=0.3, human_units=False)
            middle_field = np.diff(d_baseline.getaxis(fieldaxis)[r_[0,-1]]).item()
            d_baseline.setaxis(fieldaxis, lambda x: x-middle_field)
            c = d_baseline.polyfit(fieldaxis, order=7)
            polybaseline = d.fromaxis(fieldaxis).setaxis(fieldaxis, lambda x: x-middle_field).eval_poly(c,fieldaxis)
            polybaseline.setaxis(fieldaxis, lambda x: x+middle_field)
            fl.plot(polybaseline, alpha=0.5, human_units=False)
            fl.next("absorption, with baseline")
            d_abs -= polybaseline
            fl.plot(d_abs, alpha=0.5)
            d_abs.integrate(fieldaxis, cumulative=True)
            fl.next("dblint ÷ denom")
            fl.plot(d_abs/signal_denom.magnitude, alpha=0.5, label=f"{thislabel} (denominator ${signal_denom:~0.2L}$)")
            expected_QESR = (d_abs/signal_denom.magnitude).data[-100:].mean()
            fl.next("dblint")
            fl.plot(d_abs, alpha=0.5, label=f"{thislabel}")
            norm = d_abs.data[-100:].mean()
            myconcs.append(expected_QESR)
            fl.next("dblint, normed\n→ check for ⅓")
            fl.plot(d_abs/norm, alpha=0.5)
            if filenum == 0:
                axhline(y=0, color='k', alpha=0.2)
                axhline(y=1/3, color='k', alpha=0.2)
                axhline(y=2/3, color='k', alpha=0.2)
                axhline(y=1, color='k', alpha=0.2)
        fl.next('compare my QESR to Bruker')
        fl.plot(QESR_concs,myconcs,'x')
        myconcs.append(0) # add a point at 0,0
        m, b = np.polyfit(r_[QESR_concs,0],myconcs,1)
        myconcs = myconcs[:-1]
        x = r_[QESR_concs.min():QESR_concs.max():100j]
        fl.plot(x,m*x+b,label='m=%g b=%g'%(m,b))
        # from above m = 3.99635e-3
        m_hardcode = 3.99635e-3
        assert np.isclose(m,m_hardcode)
        for j in range(len(myconcs)):
            print("Bruker: %04.2f Ours: %04.2f"%(QESR_concs[j]/1e-6,myconcs[j]/m_hardcode/1e-6))


.. rst-class:: sphx-glr-timing

   **Total running time of the script:** ( 0 minutes  4.908 seconds)


.. _sphx_glr_download_auto_examples_QESR.py:


.. only :: html

 .. container:: sphx-glr-footer
    :class: sphx-glr-footer-example



  .. container:: sphx-glr-download sphx-glr-download-python

     :download:`Download Python source code: QESR.py <QESR.py>`



  .. container:: sphx-glr-download sphx-glr-download-jupyter

     :download:`Download Jupyter notebook: QESR.ipynb <QESR.ipynb>`


.. only:: html

 .. rst-class:: sphx-glr-signature

    `Gallery generated by Sphinx-Gallery <https://sphinx-gallery.github.io>`_
